services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe
      DB_HOST: db
    container_name: movies_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d movies_database"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./02_movies_admin
      dockerfile: Dockerfile
    container_name: movies_admin
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media

  nginx:
    image: nginx:1.27-alpine
    container_name: movies_nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/opt/app/static:ro
      - media_volume:/opt/app/media:ro

volumes:
  pg_data:
  static_volume:
  media_volume: