# Generated by Django 3.2 on 2022-07-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(null=True, verbose_name='Role'),
        ),
    ]
