# Generated by Django 5.1 on 2026-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_personfilmwork_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="movies.PersonFilmwork", to="movies.person"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("tv_show", "tv_show"), ("movie", "movie")],
                default="movie",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.TextField(
                choices=[("male", "male"), ("female", "female")],
                default=None,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("Director", "Director"),
                    ("Actor", "Actor"),
                    ("Screenwriter", "Screenwriter"),
                ],
                default="Actor",
                max_length=50,
                null=True,
                verbose_name="Role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genrefilmwork",
            unique_together={("film_work", "genre")},
        ),
        migrations.AlterUniqueTogether(
            name="personfilmwork",
            unique_together={("film_work", "person", "role")},
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(
                fields=["film_work", "genre"], name="genre_film_work_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personfilmwork",
            index=models.Index(
                fields=["film_work", "person", "role"], name="film_work_person_idx"
            ),
        ),
    ]
